//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequests
    {
        public int OrderRequestID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> OrderRequestDate { get; set; }
        public int RequestQuantity { get; set; }
        public string OrderRequestStatus { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
