//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserEmail { get; set; }
        public string Userpassword { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Username { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
