//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseTransfers
    {
        public int TransferID { get; set; }
        public Nullable<int> SourceWarehouseID { get; set; }
        public Nullable<int> DestinationWarehouseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Status { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Warehouses Warehouses { get; set; }
        public virtual Warehouses Warehouses1 { get; set; }
    }
}
